image: node:12.13.0-alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
  artifacts:
    paths:
      - public
  only:
    - dev
    - master
  tags:
    - docker_spot_runner_4-2020-static-site

deploy-dev:
  stage: deploy
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - aws s3 mv public s3://${DEV_BUCKET} --recursive --acl public-read
  only:
    - dev
  tags:
    - docker_spot_runner_4-2020-static-site

deploy-prod:
  stage: deploy
  script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli
    - aws s3 cp public s3://${PROD_BUCKET} --recursive --acl bucket-owner-full-control --metadata-directive REPLACE
  only:
    - master
  tags:
    - docker_spot_runner_4-2020-static-site
